version: '3.8'
services:

  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry

  product-service:
    build: ./product-service
    ports:
      - "8081:8080"

  order-service:
    build: ./order-service
    ports:
      - "8082:8080"

  payment-service:
    build: ./payment-service
    ports:
      - "8083:8080"

  notification-service:
    build: ./notify-service
    ports:
      - "8084:8080"
